<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Amare Tesfaw - Portfolio</title>
    <link rel="stylesheet" href="styles.css">
    <script defer src="script.js"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap');

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Poppins', sans-serif;
            background-color: #0d1117;
            color: #fff;
        }
        header {
            background: linear-gradient(90deg, #0073e6, #00bcd4);
            text-align: center;
            padding: 50px 20px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
        }
        header h1 {
            font-size: 2.5em;
        }
        nav {
            display: flex;
            justify-content: center;
            padding: 15px 0;
            background: #121212;
        }
        nav ul {
            list-style: none;
            display: flex;
            gap: 30px;
        }
        nav ul li a {
            text-decoration: none;
            color: white;
            font-weight: bold;
            transition: color 0.3s;
        }
        nav ul li a:hover {
            color: #00bcd4;
        }
        section {
            padding: 80px 20px;
            text-align: center;
        }
        .container {
            width: 80%;
            margin: auto;
        }
        .project-container {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 20px;
        }
        .project {
            background: #1e1e1e;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);
            transition: transform 0.3s, background 0.3s;
        }
        .project:hover {
            transform: scale(1.05);
            background: #292929;
        }
        .contact {
            background: #0073e6;
            padding: 40px;
            border-radius: 10px;
            display: inline-block;
        }
        .contact a {
            color: #fff;
            text-decoration: none;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <header>
        <h1>Amare Tesfaw</h1>
        <p>Full-Stack Developer | Researcher | Lecturer</p>
    </header>
    
    <nav>
        <ul>
            <li><a href="#home">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#projects">Projects</a></li>
            <li><a href="#contact">Contact</a></li>
        </ul>
    </nav>
    
    <section id="home">
        <div class="container">
            <h2>Welcome to My Portfolio</h2>
            <p>Passionate about building scalable applications and AI solutions.</p>
        </div>
    </section>
    
    <section id="about">
        <div class="container">
            <h2>About Me</h2>
            <p>I'm an IT professional specializing in full-stack development, AI, and research.</p>
        </div>
    </section>
    
    <section id="projects">
        <div class="container">
            <h2>Projects</h2>
            <div class="project-container">
                <div class="project">
                    <h3>AI-Based Course Recommender</h3>
                    <p>Built with Python, Machine Learning, and Spring Boot.</p>
                </div>
                <div class="project">
                    <h3>Personal Schedule App</h3>
                    <p>Developed using React and SQL Server for efficient scheduling.</p>
                </div>
            </div>
        </div>
    </section>
    
    <section id="contact">
        <div class="container">
            <h2>Contact Me</h2>
            <div class="contact">
                <p>Email: example@email.com</p>
                <p>GitHub: <a href="#">github.com/amaretesfaw</a></p>
            </div>
        </div>
    </section>
</body>
</html>
